var Sf17179Web = (() => {
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,ea,fa,ha=new Promise((a,b)=>{ea=a;fa=b}),ia="object"==typeof window,k="undefined"!=typeof WorkerGlobalScope,l=k&&self.name?.startsWith("em-pthread");h.listen||(h.listen=a=>console.log(a));h.onError||(h.onError=a=>console.error(a));h.getRecommendedNnue=(a=0)=>ja(ka(a));
h.setNnueBuffer=function(a,b=0){if(!a)throw Error("buf is null");if(0>=a.byteLength)throw Error(`${a.byteLength} bytes?`);const c=la(a.byteLength);if(!c)throw Error(`could not allocate ${a.byteLength} bytes`);h.HEAPU8.set(a,c);ma(c,a.byteLength,b)};h.uci=function(a){const b=na(a)+1,c=la(b);if(!c)throw Error(`Could not allocate ${b} bytes`);m(a,c,b);oa(c)};h.print=a=>h.listen?.(a);h.printErr=a=>h.onError?.(a);var pa=[],qa=import.meta.url,ra="",sa,ua;
if(ia||k){try{ra=(new URL(".",qa)).href}catch{}k&&(ua=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});sa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var va=console.log.bind(console),q=console.error.bind(console),r,wa,xa=!1,u,v,ya,za,w,y,z,Aa,Ba=!1;function A(){r.buffer!=v.buffer&&Ca()}var Da;
if(l){var Ea=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.la;if("load"===d){let e=[];self.onmessage=f=>e.push(f);self.startWorker=()=>{postMessage({la:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Xa)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({la:"callHandler",Wa:f,Ua:g})},"print"==f&&(va=h[f]),"printErr"==f&&(q=h[f]);r=c.jb;Ca();Da(c.kb)}else if("run"===d){Fa(c.ja);Ga(c.ja,0,0,1,0,0);Ha();Ia(c.ja);Ea||=!0;try{Ja(c.fb,c.Ca)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?Ea&&Ka():d&&(q(`worker: received unknown command ${d}`),q(c)))}catch(e){throw La(),e;}}self.onmessage=a}function Ca(){var a=r.buffer;v=new Int8Array(a);za=new Int16Array(a);h.HEAPU8=ya=new Uint8Array(a);new Uint16Array(a);w=new Int32Array(a);y=new Uint32Array(a);new Float32Array(a);Aa=new Float64Array(a);z=new BigInt64Array(a);new BigUint64Array(a)}
function Ma(){l?startWorker(h):(h.noFSInit||Na||(Na=!0,Oa("/dev/tty","/dev/stdin"),Oa("/dev/tty","/dev/stdout"),Oa("/dev/tty1","/dev/stderr"),Pa("/dev/stdin",0),Pa("/dev/stdout",1),Pa("/dev/stderr",1)),B.E(),Qa=!1)}var C=0,D=null;function Ra(){C--;if(0==C&&D){var a=D;D=null;a()}}function Sa(a){a="Aborted("+a+")";q(a);xa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");fa(a);throw a;}var Ta;
async function Ua(a){try{var b=await sa(a);return new Uint8Array(b)}catch{}if(ua)a=ua(a);else throw"both async and sync fetching of the wasm failed";return a}async function Va(a,b){try{var c=await Ua(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),Sa(d)}}
async function Wa(a){var b=Ta;if("function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return Va(b,a)}function Xa(){Ya={C:Za,f:$a,x:ab,y:bb,m:cb,k:db,B:eb,i:fb,o:gb,g:hb,j:Ia,h:ib,p:jb,r:kb,D:lb,d:mb,l:nb,c:ob,q:pb,A:qb,v:rb,s:sb,t:tb,b:ub,e:vb,w:wb,u:xb,z:yb,a:r,n:zb};return{a:Ya}}
class Ab{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Bb=a=>{a.terminate();a.onmessage=()=>{}},Cb=[],Fb=a=>{0==G.length&&(Db(),Eb(G[0]));var b=G.pop();if(!b)return 6;H.push(b);I[a.ja]=b;b.ja=a.ja;b.postMessage({la:"run",fb:a.eb,Ca:a.Ca,ja:a.ja},a.Sa);return 0},J=0,rb=()=>0<J,K=(a,b,...c)=>{for(var d=2*c.length,e=Gb(),f=Hb(8*d),g=f>>3,n=0;n<c.length;n++){var t=c[n];"bigint"==typeof t?((A(),z)[g+2*n]=1n,(A(),z)[g+2*n+1]=t):((A(),z)[g+2*n]=0n,(A(),Aa)[g+2*n+1]=t)}a=Ib(a,0,d,f,b);Jb(e);return a};
function zb(a){if(l)return K(0,1,a);u=a;0<J||(Kb(),xa=!0);throw new Ab(a);}function Lb(a){if(l)return K(1,0,a);--J;ub(a)}var ub=a=>{u=a;if(l)throw Lb(a),"unwind";if(!(0<J||l)){Mb();Na=!1;Nb(0);for(var b of L)b&&Ob(b);Kb();Ba=!0}zb(a)},G=[],H=[],Pb=[],I={};function Qb(){for(var a=navigator.hardwareConcurrency;a--;)Db();Cb.push(()=>{C++;Rb(()=>Ra())})}var Kb=()=>{for(var a of H)Bb(a);for(a of G)Bb(a);G=[];H=[];I={}},Tb=a=>{var b=a.ja;delete I[b];G.push(a);H.splice(H.indexOf(a),1);a.ja=0;Sb(b)};
function Ha(){Pb.forEach(a=>a())}
var Eb=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.la;if(f.Ba&&f.Ba!=Ub()){var n=I[f.Ba];n?n.postMessage(f,f.Sa):q(`Internal error! Worker sent a message "${g}" to target pthread ${f.Ba}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ka();else if("spawnThread"===g)Fb(f);else if("cleanupThread"===g)Tb(I[f.gb]);else if("loaded"===g)a.loaded=!0,b(a);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)h[f.Wa](...f.Ua);else g&&q(`worker sent an unknown command ${g}`)};
a.onerror=f=>{q(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({la:"load",Xa:c,jb:r,kb:wa})});function Rb(a){l?a():Promise.all(G.map(Eb)).then(a)}
function Db(){if(h.mainScriptUrlOrBlob){var a=h.mainScriptUrlOrBlob;"string"!=typeof a&&(a=URL.createObjectURL(a));a=new Worker(a,{type:"module",name:"em-pthread"})}else a=new Worker(new URL("sf171-79.js",import.meta.url),{type:"module",name:"em-pthread"});G.push(a)}var Fa=a=>{var b=(A(),y)[a+52>>2];a=(A(),y)[a+56>>2];Vb(b,b-a);Jb(b)},Wb=[],Xb,Ja=(a,b)=>{J=0;var c=Wb[a];c||(Wb[a]=c=Xb.get(a));a=c(b);0<J?u=a:Yb(a)};function Zb(a,b,c,d){return l?K(2,1,a,b,c,d):Za(a,b,c,d)}
var Za=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(l&&0===e.length)return Zb(a,b,c,d);a={eb:c,ja:a,Ca:d,Sa:e};return l?(a.la="spawnThread",postMessage(a,e),0):Fb(a)},N=()=>{var a=(A(),w)[+M>>2];M+=4;return a},$b=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ac=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=$b(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},bc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},cc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),dc=a=>{(dc=cc())(a)},ec=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
$b(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},fc="undefined"!=typeof TextDecoder?new TextDecoder:void 0,P=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&fc)return fc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},gc=[],na=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},hc=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},ic=[];function jc(a,b){ic[a]={input:[],output:[],na:b};kc(a,lc)}
var lc={open(a){var b=ic[a.node.za];if(!b)throw new Q(43);a.da=b;a.seekable=!1},close(a){a.da.na.wa(a.da)},wa(a){a.da.na.wa(a.da)},read(a,b,c,d){if(!a.da||!a.da.na.La)throw new Q(60);for(var e=0,f=0;f<d;f++){try{var g=a.da.na.La(a.da)}catch(n){throw new Q(29);}if(void 0===g&&0===e)throw new Q(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.ra=Date.now());return e},write(a,b,c,d){if(!a.da||!a.da.na.Ga)throw new Q(60);try{for(var e=0;e<d;e++)a.da.na.Ga(a.da,b[c+e])}catch(f){throw new Q(29);
}d&&(a.node.ga=a.node.fa=Date.now());return e}},mc={La(){a:{if(!gc.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(na(a)+1);a=hc(a,b,0,b.length);b.length=a;gc=b}b=gc.shift()}return b},Ga(a,b){null===b||10===b?(va(P(a.output)),a.output=[]):0!=b&&a.output.push(b)},wa(a){0<a.output?.length&&(va(P(a.output)),a.output=[])},Za(){return{pb:25856,rb:5,ob:191,qb:35387,nb:[3,28,127,21,4,0,1,0,
17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},$a(){return 0},ab(){return[24,80]}},nc={Ga(a,b){null===b||10===b?(q(P(a.output)),a.output=[]):0!=b&&a.output.push(b)},wa(a){0<a.output?.length&&(q(P(a.output)),a.output=[])}},R={ia:null,ma(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.ia||(R.ia={dir:{node:{qa:R.ca.qa,ka:R.ca.ka,ta:R.ca.ta,xa:R.ca.xa,Qa:R.ca.Qa,Ta:R.ca.Ta,Ra:R.ca.Ra,Ha:R.ca.Ha,Aa:R.ca.Aa},stream:{ha:R.aa.ha}},
file:{node:{qa:R.ca.qa,ka:R.ca.ka},stream:{ha:R.aa.ha,read:R.aa.read,write:R.aa.write,Na:R.aa.Na,Pa:R.aa.Pa}},link:{node:{qa:R.ca.qa,ka:R.ca.ka,ua:R.ca.ua},stream:{}},Ja:{node:{qa:R.ca.qa,ka:R.ca.ka},stream:oc}});c=pc(a,b,c,d);16384===(c.mode&61440)?(c.ca=R.ia.dir.node,c.aa=R.ia.dir.stream,c.ba={}):32768===(c.mode&61440)?(c.ca=R.ia.file.node,c.aa=R.ia.file.stream,c.ea=0,c.ba=null):40960===(c.mode&61440)?(c.ca=R.ia.link.node,c.aa=R.ia.link.stream):8192===(c.mode&61440)&&(c.ca=R.ia.Ja.node,c.aa=R.ia.Ja.stream);
c.ra=c.ga=c.fa=Date.now();a&&(a.ba[b]=c,a.ra=a.ga=a.fa=c.ra);return c},vb(a){return a.ba?a.ba.subarray?a.ba.subarray(0,a.ea):new Uint8Array(a.ba):new Uint8Array(0)},ca:{qa(a){var b={};b.sb=8192===(a.mode&61440)?a.id:1;b.xb=a.id;b.mode=a.mode;b.yb=1;b.uid=0;b.wb=0;b.za=a.za;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ea:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ra=new Date(a.ra);b.ga=new Date(a.ga);b.fa=new Date(a.fa);b.Va=4096;b.mb=Math.ceil(b.size/b.Va);return b},
ka(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ea!=b&&(0==b?(a.ba=null,a.ea=0):(c=a.ba,a.ba=new Uint8Array(b),c&&a.ba.set(c.subarray(0,Math.min(b,a.ea))),a.ea=b)))},ta(){throw R.Ka;},xa(a,b,c,d){return R.createNode(a,b,c,d)},Qa(a,b,c){try{var d=qc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.ba)throw new Q(55);e=rc(d.parent.id,d.name);if(S[e]===d)S[e]=d.sa;else for(e=S[e];e;){if(e.sa===d){e.sa=d.sa;break}e=e.sa}}delete a.parent.ba[a.name];
b.ba[c]=a;a.name=c;b.fa=b.ga=a.parent.fa=a.parent.ga=Date.now()},Ta(a,b){delete a.ba[b];a.fa=a.ga=Date.now()},Ra(a,b){var c=qc(a,b),d;for(d in c.ba)throw new Q(55);delete a.ba[b];a.fa=a.ga=Date.now()},Ha(a){return[".","..",...Object.keys(a.ba)]},Aa(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},ua(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},aa:{read(a,b,c,d,e){var f=a.node.ba;if(e>=a.node.ea)return 0;a=Math.min(a.node.ea-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=
0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===(A(),v).buffer&&(f=!1);if(!d)return 0;a=a.node;a.ga=a.fa=Date.now();if(b.subarray&&(!a.ba||a.ba.subarray)){if(f)return a.ba=b.subarray(c,c+d),a.ea=d;if(0===a.ea&&0===e)return a.ba=b.slice(c,c+d),a.ea=d;if(e+d<=a.ea)return a.ba.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.ba?a.ba.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.ba,a.ba=new Uint8Array(f),0<a.ea&&a.ba.set(g.subarray(0,a.ea),0));if(a.ba.subarray&&
b.subarray)a.ba.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ba[e+f]=b[c+f];a.ea=Math.max(a.ea,e+d);return d},ha(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ea);if(0>b)throw new Q(28);return b},Na(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.ba;if(e&2||!a||a.buffer!==(A(),v).buffer){d=!0;Sa();e=void 0;if(!e)throw new Q(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);(A(),v).set(a,e)}}else d=
!1,e=a.byteOffset;return{Ab:e,lb:d}},Pa(a,b,c,d){R.aa.write(a,b,0,d,c,!1);return 0}}},sc=a=>{var b=0;a&&(b|=365);return b},tc=null,uc={},L=[],vc=1,S=null,Na=!1,Qa=!0,Q=class{name="ErrnoError";constructor(a){this.oa=a}},wc=class{va={};node=null;get flags(){return this.va.flags}set flags(a){this.va.flags=a}get position(){return this.va.position}set position(a){this.va.position=a}},xc=class{ca={};aa={};ya=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ma=a.ma;this.id=vc++;this.name=b;this.mode=
c;this.za=d;this.ra=this.ga=this.fa=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function T(a,b={}){if(!a)throw new Q(44);b.Ea??(b.Ea=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=tc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=bc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=ac(e+"/"+a[f]);try{d=qc(d,a[f])}catch(n){if(44===n?.oa&&g&&b.cb)return{path:e};throw n;}!d.ya||g&&!b.Ea||(d=d.ya.root);if(40960===(d.mode&61440)&&(!g||b.Da)){if(!d.ca.ua)throw new Q(52);
d=d.ca.ua(d);"/"===d.charAt(0)||(d=bc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new Q(32);}function rc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function qc(a,b){var c=16384===(a.mode&61440)?(c=yc(a,"x"))?c:a.ca.ta?0:2:54;if(c)throw new Q(c);for(c=S[rc(a.id,b)];c;c=c.sa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ca.ta(a,b)}
function pc(a,b,c,d){a=new xc(a,b,c,d);b=rc(a.parent.id,a.name);a.sa=S[b];return S[b]=a}function zc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yc(a,b){if(Qa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ac(a,b){if(16384!==(a.mode&61440))return 54;try{return qc(a,b),20}catch(c){}return yc(a,"wx")}function U(a){a=L[a];if(!a)throw new Q(8);return a}
function Bc(a,b=-1){a=Object.assign(new wc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!L[b])break a;throw new Q(33);}a.pa=b;return L[b]=a}function Cc(a,b=-1){a=Bc(a,b);a.aa?.ub?.(a);return a}function Dc(a,b){var c=null?.aa.ka,d=c?null:a;c??=a.ca.ka;if(!c)throw new Q(63);c(d,b)}var oc={open(a){a.aa=uc[a.node.za].aa;a.aa.open?.(a)},ha(){throw new Q(70);}};function kc(a,b){uc[a]={aa:b}}
function Ec(a,b){var c="/"===b;if(c&&tc)throw new Q(10);if(!c&&b){var d=T(b,{Ea:!1});b=d.path;d=d.node;if(d.ya)throw new Q(10);if(16384!==(d.mode&61440))throw new Q(54);}b={type:a,zb:{},Oa:b,bb:[]};a=a.ma(b);a.ma=b;b.root=a;c?tc=a:d&&(d.ya=b,d.ma&&d.ma.bb.push(b))}function Fc(a,b,c){var d=T(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new Q(28);if("."===a||".."===a)throw new Q(20);var e=Ac(d,a);if(e)throw new Q(e);if(!d.ca.xa)throw new Q(63);return d.ca.xa(d,a,b,c)}
function V(a){return Fc(a,16895,0)}function Gc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Fc(a,b|8192,c)}function Oa(a,b){if(!ec(a))throw new Q(44);var c=T(b,{parent:!0}).node;if(!c)throw new Q(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ac(c,b);if(d)throw new Q(d);if(!c.ca.Aa)throw new Q(63);c.ca.Aa(c,b,a)}
function Pa(a,b,c=438){if(""===a)throw new Q(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=T(a,{Da:!(b&131072),cb:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new Q(20);}else{if(e)throw new Q(31);d=Fc(a,c|511,0);f=!0}if(!d)throw new Q(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&
61440))throw new Q(54);if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==zc(b)||b&576)?31:yc(d,zc(b)):44))throw new Q(e);if(b&512&&!f){e=d;e="string"==typeof e?T(e,{Da:!0}).node:e;if(16384===(e.mode&61440))throw new Q(31);if(32768!==(e.mode&61440))throw new Q(28);if(a=yc(e,"w"))throw new Q(a);Dc(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.ma.Oa;var g=g?"/"!==e[e.length-1]?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}b=Bc({node:d,path:g,
flags:b&-131713,seekable:!0,position:0,aa:d.aa,hb:[],error:!1});b.aa.open&&b.aa.open(b);f&&(c&=511,d="string"==typeof d?T(d,{Da:!0}).node:d,Dc(d,{mode:c&4095|d.mode&-4096,fa:Date.now(),tb:void 0}));return b}function Ob(a){if(null===a.pa)throw new Q(8);a.Fa&&(a.Fa=null);try{a.aa.close&&a.aa.close(a)}catch(b){throw b;}finally{L[a.pa]=null}a.pa=null}
function Hc(a,b,c){if(null===a.pa)throw new Q(8);if(!a.seekable||!a.aa.ha)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.aa.ha(a,b,c);a.hb=[]}
function W(a,b){a=ac("/dev/"+a);var c=sc(!!b);W.Ma??(W.Ma=64);var d=W.Ma++<<8|0;kc(d,{open(e){e.seekable=!1},close(){(void 0)?.buffer?.length&&(void 0)(10)},read(e,f,g,n){for(var t=0,p=0;p<n;p++){try{var x=b()}catch(ta){throw new Q(29);}if(void 0===x&&0===t)throw new Q(6);if(null===x||void 0===x)break;t++;f[g+p]=x}t&&(e.node.ra=Date.now());return t},write(e,f,g,n){for(var t=0;t<n;t++)try{(void 0)(f[g+t])}catch(p){throw new Q(29);}n&&(e.node.ga=e.node.fa=Date.now());return t}});Gc(a,c,d)}
var X={},ja=(a,b)=>a?P((A(),ya),a,b):"",M=void 0;function $a(a,b,c){if(l)return K(3,1,a,b,c);M=c;try{var d=U(a);switch(b){case 0:var e=N();if(0>e)break;for(;L[e];)e++;return Cc(d,e).pa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=N(),d.flags|=e,0;case 12:return e=N(),(A(),za)[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof X||"ErrnoError"!==f.name)throw f;return-f.oa}}
function ab(a,b,c){if(l)return K(4,1,a,b,c);M=c;try{var d=U(a);switch(b){case 21509:return d.da?0:-59;case 21505:if(!d.da)return-59;if(d.da.na.Za){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=N();(A(),w)[e>>2]=25856;(A(),w)[e+4>>2]=5;(A(),w)[e+8>>2]=191;(A(),w)[e+12>>2]=35387;for(var f=0;32>f;f++)(A(),v)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.da?0:-59;case 21506:case 21507:case 21508:if(!d.da)return-59;if(d.da.na.$a)for(e=N(),A(),
A(),A(),A(),a=[],f=0;32>f;f++)a.push((A(),v)[e+f+17]);return 0;case 21519:if(!d.da)return-59;e=N();return(A(),w)[e>>2]=0;case 21520:return d.da?-28:-59;case 21531:e=N();if(!d.aa.Ya)throw new Q(59);return d.aa.Ya(d,b,e);case 21523:if(!d.da)return-59;d.da.na.ab&&(f=[24,80],e=N(),(A(),za)[e>>1]=f[0],(A(),za)[e+2>>1]=f[1]);return 0;case 21524:return d.da?0:-59;case 21515:return d.da?0:-59;default:return-28}}catch(g){if("undefined"==typeof X||"ErrnoError"!==g.name)throw g;return-g.oa}}
function bb(a,b,c,d){if(l)return K(5,1,a,b,c,d);M=d;try{b=ja(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":U(a).path;if(0==e.length)throw new Q(44);b=f+"/"+e}var g=d?N():0;return Pa(b,c,g).pa}catch(n){if("undefined"==typeof X||"ErrnoError"!==n.name)throw n;return-n.oa}}
var cb=()=>Sa(""),db=a=>{Ga(a,!k,1,!ia,3145728,!1);Ha()},Ic=a=>{if(!(a instanceof Ab||"unwind"==a))throw a;},Jc=a=>{if(!Ba&&!xa)try{if(a(),!(Ba||0<J))try{l?Yb(u):ub(u)}catch(b){Ic(b)}}catch(b){Ic(b)}},Ia=a=>{"function"===typeof Atomics.ib&&(Atomics.ib((A(),w),a>>2,a).value.then(Ka),a+=128,Atomics.store((A(),w),a>>2,1))},Ka=()=>{var a=Ub();a&&(Ia(a),Jc(Kc))},eb=(a,b)=>{a==b?setTimeout(Ka):l?postMessage({Ba:a,la:"checkMailbox"}):(a=I[a])&&a.postMessage({la:"checkMailbox"})},Lc=[],fb=(a,b,c,d,e)=>{d/=
2;Lc.length=d;b=e>>3;for(c=0;c<d;c++)(A(),z)[b+2*c]?Lc[c]=(A(),z)[b+2*c+1]:Lc[c]=(A(),Aa)[b+2*c+1];return(0,Mc[a])(...Lc)},gb=()=>{J=0},hb=a=>{l?postMessage({la:"cleanupThread",gb:a}):Tb(I[a])},ib=()=>{},Y={},ob=()=>performance.timeOrigin+performance.now();function jb(a,b){if(l)return K(6,1,a,b);Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];Jc(()=>Nc(a,performance.timeOrigin+performance.now()))},b);Y[a]={id:c,Bb:b};return 0}
var m=(a,b,c)=>hc(a,(A(),ya),b,c),kb=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(A(),y)[a>>2]=60*g;(A(),w)[b>>2]=Number(f!=e);b=n=>{var t=Math.abs(n);return`UTC${0<=n?"-":"+"}${String(Math.floor(t/60)).padStart(2,"0")}${String(t%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(m(a,c,17),m(b,d,17)):(m(a,d,17),m(b,c,17))},Oc=1;
function lb(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Oc)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(A(),z)[c>>3]=BigInt(a);return 0}
var Z=()=>{Z.Ia||(Z.Ia={});Z.Ia["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Z.Ia["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,q("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},mb=()=>{k||(Z(),Sa("Blocking on the main thread is not allowed by default. See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},
nb=()=>{J+=1;throw"unwind";},pb=()=>navigator.hardwareConcurrency,qb=a=>{var b=(A(),ya).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-r.buffer.byteLength+65535)/65536|0;try{r.grow(d);Ca();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Pc={},Rc=()=>{if(!Qc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&
navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Pc)void 0===Pc[b]?delete a[b]:a[b]=Pc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qc=c}return Qc},Qc;function sb(a,b){if(l)return K(7,1,a,b);var c=0,d=0,e;for(e of Rc()){var f=b+c;(A(),y)[a+d>>2]=f;c+=m(e,f,Infinity)+1;d+=4}return 0}function tb(a,b){if(l)return K(8,1,a,b);var c=Rc();(A(),y)[a>>2]=c.length;a=0;for(var d of c)a+=na(d)+1;(A(),y)[b>>2]=a;return 0}
function vb(a){if(l)return K(9,1,a);try{var b=U(a);Ob(b);return 0}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return c.oa}}
function wb(a,b,c,d){if(l)return K(10,1,a,b,c,d);try{a:{var e=U(a);a=b;for(var f,g=b=0;g<c;g++){var n=(A(),y)[a>>2],t=(A(),y)[a+4>>2];a+=8;var p=e,x=(A(),v),ta=n,aa=t,E=f;if(0>aa||0>E)throw new Q(28);if(null===p.pa)throw new Q(8);if(1===(p.flags&2097155))throw new Q(8);if(16384===(p.node.mode&61440))throw new Q(31);if(!p.aa.read)throw new Q(28);var ba="undefined"!=typeof E;if(!ba)E=p.position;else if(!p.seekable)throw new Q(70);var ca=p.aa.read(p,x,ta,aa,E);ba||(p.position+=ca);var F=ca;if(0>F){var da=
-1;break a}b+=F;if(F<t)break;"undefined"!=typeof f&&(f+=F)}da=b}(A(),y)[d>>2]=da;return 0}catch(O){if("undefined"==typeof X||"ErrnoError"!==O.name)throw O;return O.oa}}function xb(a,b,c,d){if(l)return K(11,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=U(a);Hc(e,b,c);(A(),z)[d>>3]=BigInt(e.position);e.Fa&&0===b&&0===c&&(e.Fa=null);return 0}catch(f){if("undefined"==typeof X||"ErrnoError"!==f.name)throw f;return f.oa}}
function yb(a,b,c,d){if(l)return K(12,1,a,b,c,d);try{a:{var e=U(a);a=b;for(var f,g=b=0;g<c;g++){var n=(A(),y)[a>>2],t=(A(),y)[a+4>>2];a+=8;var p=e,x=(A(),v),ta=n,aa=t,E=f;if(0>aa||0>E)throw new Q(28);if(null===p.pa)throw new Q(8);if(0===(p.flags&2097155))throw new Q(8);if(16384===(p.node.mode&61440))throw new Q(31);if(!p.aa.write)throw new Q(28);p.seekable&&p.flags&1024&&Hc(p,0,2);var ba="undefined"!=typeof E;if(!ba)E=p.position;else if(!p.seekable)throw new Q(70);var ca=p.aa.write(p,x,ta,aa,E,void 0);
ba||(p.position+=ca);var F=ca;if(0>F){var da=-1;break a}b+=F;if(F<t)break;"undefined"!=typeof f&&(f+=F)}da=b}(A(),y)[d>>2]=da;return 0}catch(O){if("undefined"==typeof X||"ErrnoError"!==O.name)throw O;return O.oa}}l||Qb();S=Array(4096);Ec(R,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");kc(259,{read:()=>0,write:(d,e,f,g)=>g,ha:()=>0});Gc("/dev/null",259);jc(1280,mc);jc(1536,nc);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(dc(a),b=a.byteLength);return a[--b]};W("random",c);W("urandom",c);V("/dev/shm");V("/dev/shm/tmp")})();
(function(){V("/proc");var a=V("/proc/self");V("/proc/self/fd");Ec({ma(){var b=pc(a,"fd",16895,73);b.aa={ha:R.aa.ha};b.ca={ta(c,d){c=+d;var e=U(c);c={parent:null,ma:{Oa:"fake"},ca:{ua:()=>e.path},id:c+1};return c.parent=c},Ha(){return Array.from(L.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();R.Ka=new Q(44);R.Ka.stack="<generic error, no stack>";l||(h.wasmMemory?r=h.wasmMemory:r=new WebAssembly.Memory({initial:1024,maximum:32768,shared:!0}),Ca());
h.print&&(va=h.print);h.printErr&&(q=h.printErr);h.UTF8ToString=ja;h.stringToUTF8=m;
var Mc=[zb,Lb,Zb,$a,ab,bb,jb,sb,tb,vb,wb,xb,yb],Ya,B=await (async function(){function a(d,e){B=d.exports;Pb.push(B.K);Xb=B.N;wa=e;Ra();return B}C++;var b=Xa();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(l)return new Promise(d=>{Da=e=>{var f=new WebAssembly.Instance(e,Xa());d(a(f,e))}});Ta??=h.locateFile?h.locateFile?h.locateFile("sf171-79.wasm",ra):ra+"sf171-79.wasm":(new URL("sf171-79.wasm",import.meta.url)).href;try{var c=await Wa(b);
return a(c.instance,c.module)}catch(d){return fa(d),Promise.reject(d)}}());h._main=(a,b)=>(h._main=B.F)(a,b);h.__Z10js_getlinev=a=>(h.__Z10js_getlinev=B.G)(a);
var oa=h._uci=a=>(oa=h._uci=B.H)(a),ma=h._setNnueBuffer=(a,b,c)=>(ma=h._setNnueBuffer=B.I)(a,b,c),ka=h._getRecommendedNnue=a=>(ka=h._getRecommendedNnue=B.J)(a),Ub=()=>(Ub=B.L)(),Sc=h.__emscripten_proxy_main=(a,b)=>(Sc=h.__emscripten_proxy_main=B.M)(a,b),Mb=()=>(Mb=B.O)(),Ga=(a,b,c,d,e,f)=>(Ga=B.P)(a,b,c,d,e,f),La=()=>(La=B.Q)(),Nb=a=>(Nb=B.R)(a),la=h._malloc=a=>(la=h._malloc=B.S)(a),Ib=(a,b,c,d,e)=>(Ib=B.T)(a,b,c,d,e),Sb=a=>(Sb=B.U)(a),Yb=a=>(Yb=B.V)(a),Nc=(a,b)=>(Nc=B.W)(a,b),Kc=()=>(Kc=B.X)(),Vb=
(a,b)=>(Vb=B.Y)(a,b),Jb=a=>(Jb=B.Z)(a),Hb=a=>(Hb=B._)(a),Gb=()=>(Gb=B.$)();function Tc(a=[]){var b=Sc;J+=1;a.unshift("./this.program");var c=a.length,d=Hb(4*(c+1)),e=d;a.forEach(g=>{var n=(A(),y),t=e>>2,p=na(g)+1,x=Hb(p);m(g,x,p);n[t]=x;e+=4});(A(),y)[e>>2]=0;try{var f=b(c,d);ub(f,!0)}catch(g){Ic(g)}}function Uc(a=pa){if(0<C)D=Uc;else if(l)ea(h),Ma();else{for(;0<Cb.length;)Cb.shift()(h);0<C?D=Uc:(h.calledRun=!0,xa||(Ma(),ea(h),Tc(a)))}}Uc();moduleRtn=ha;


  return moduleRtn;
}
);
})();
export default Sf17179Web;
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
// When running as a pthread, construct a new instance on startup
isPthread && Sf17179Web();
